name: iot_btl
description: "A new Flutter project."


publish_to: 'none' 













version: 1.0.0+1

environment:
  sdk: ^3.5.1







dependencies:
  flutter:
    sdk: flutter


  
  
  cupertino_icons: ^1.0.8
  firebase_core: ^3.6.0
  firebase_database: ^11.1.4
  google_fonts: ^6.2.1
  sleek_circular_slider: ^2.0.1
  flutter_overlay_window: ^0.4.5
  flutter_ringtone_player: ^3.2.0
  flutter_background_service: ^5.0.10
  socket_io_client: ^3.0.2
  local_auth: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  
  
  
  
  flutter_lints: ^4.0.0





flutter:

  
  
  
  uses-material-design: true

  
  assets:
    - assets/
    - assets/audios/

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
